# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mwCd2ywAOvaMrRO0xe1NfJfzt0huRjoX
"""

catalogo = []
while True:
  print("\n Minha WatchList/ReadList")
  print("1. Adicionar título")
  print("2. Ver minha lista")
  print("3. Remover")
  print("4. Sair")
  opcao = input("Escolha uma opção: ")
  if opcao =="1":
    titulo = input("Digite o título: ")
    catalogo.append(titulo)
  elif opcao == "2":
    print("Minha lista:")
    for titulo in catalogo:
        print(titulo)
  elif opcao == "3":
    titulo = input("Digite o título a ser removido: ")
    if titulo in catalogo:
      catalogo.remove(titulo)
      print(f"{titulo} removido com sucesso!")
  elif opcao == "4":
    print("Saindo do programa...")